server:
  port: 8080
  servlet:
    context-path: /springboot
girl:
  name: B
  age: 18
  content: content:${name},age:${age}
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lttest?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: tom7323548
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false