spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lttest?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: tom7323548

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true